### ISSUE TITLE
Make library compatible with SvelteKit

### ISSUE THREAD

**Issue by hmajid2301** [vincentlaucsb/svelte-context-menu#3]
I am trying to use this library with SvelteKit but am facing issues with the SSR. It seems to be related to `document`  .
Great library btw :smile: 

```
package         files    time     avg
bookmarkey-gui    290   0.47s   1.6ms
ReferenceError: document is not defined
    at eval (/node_modules/.pnpm/svelte-contextmenu@1.0.2/node_modules/svelte-contextmenu/Menu.svelte:44:12)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.1/node_modules/svelte/internal/index.mjs:1894:22)
    at eval (/src/lib/components/organisms/AvatarProfileMenu.svelte:45:92)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.1/node_modules/svelte/internal/index.mjs:1894:22)
    at eval (/src/lib/components/organisms/SideBar.svelte:41:129)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.1/node_modules/svelte/internal/index.mjs:1894:22)
    at eval (/src/routes/my/+layout.svelte:46:456)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.1/node_modules/svelte/internal/index.mjs:1894:22)
    at Object.default (/.svelte-kit/generated/root.svelte:87:133)
    at eval (/src/routes/+layout.svelte:59:146)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.1/node_modules/svelte/internal/index.mjs:1894:22)
    at eval (/.svelte-kit/generated/root.svelte:75:129)
    at $$render (/node_modules/.pnpm/svelte@3.55.1/node_modules/svelte/internal/index.mjs:1894:22)
    at Object.render (/node_modules/.pnpm/svelte@3.55.1/node_modules/svelte/internal/index.mjs:1902:26)
    at Module.render_response (/node_modules/.pnpm/@sveltejs+kit@1.11.0_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:196:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.render_page (/node_modules/.pnpm/@sveltejs+kit@1.11.0_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:294:10)
    at async resolve (/node_modules/.pnpm/@sveltejs+kit@1.11.0_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/runtime/server/respond.js:377:17)
    at async Object.handle (/src/hooks.server.ts:51:20)
    at async Module.respond (/node_modules/.pnpm/@sveltejs+kit@1.11.0_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/runtime/server/respond.js:248:20)
    at async file:///home/haseeb/projects/bookmarkey/gui/node_modules/.pnpm/@sveltejs+kit@1.11.0_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:505:22
18:40:36 [vite-plugin-svelte] ssr compile in progress ...
```

Where one of my components `AvatarProfileMenu` looks like this

```svelte
<script lang="ts">
	import BookmarkSolid from "svelte-awesome-icons/BookmarkSolid.svelte";
	import CaretDownSolid from "svelte-awesome-icons/CaretDownSolid.svelte";
	import GearSolid from "svelte-awesome-icons/GearSolid.svelte";
	import RightFromBracketSolid from "svelte-awesome-icons/RightFromBracketSolid.svelte";

	import ContextMenu, { Item } from "svelte-contextmenu";
	import Avatar from "~/lib/components/atoms/Avatar.svelte";

	let contextMenu: ContextMenu;
	export let nickname: string;
	export let avatar: string;
	export let email: string;
</script>

<button
	aria-label="avatar"
	on:click={contextMenu.createHandler()}
	class="max-h-screen-menu static my-1 flex w-full bg-slate-100 dark:bg-slate-800 lg:overflow-y-visible">
	<div
		class="relative flex cursor-pointer items-center py-2 px-3 text-black hover:text-slate-500 dark:text-white dark:hover:text-slate-400">
		<div
			class="flex items-center bg-gray-100 bg-transparent dark:bg-slate-800 dark:bg-transparent">
			<div class="mr-3 inline-flex h-6 w-6">
				<Avatar {avatar} {nickname} {email} />
			</div>
		</div>
		<p class="flex w-32 flex-row truncate text-xs">
			{nickname}
		</p>
		<CaretDownSolid class="h-4 w-4" />
		<ContextMenu bind:this={contextMenu}>
			<Item href="/my/collections/0">
				<BookmarkSolid />
				Bookmarks
			</Item>
			<Item href="/my/settings">
				<GearSolid />
				Settings
			</Item>
			<Item href="/logout">
				<RightFromBracketSolid />
				Log Out
			</Item>
		</ContextMenu>
	</div>
</button>
```

Is there any way to get this to work with SvelteKit? I'm happy to try to implement myself if you point me in the right direction.

Related MR: https://gitlab.com/bookmarkey/gui/-/merge_requests/139

**Comment by hmajid2301** [comment]
Seems to be related to `Menu.svelte`   the object at the top. Commenting it out at least lets the app load.

```
const CLOSE_LISTENERS = {
    // "click": document.body,
    // "contextmenu": document.body,
    // "scroll": document
};
````

**Comment by hmajid2301** [comment]
already a fix here: https://github.com/vincentlaucsb/svelte-contextmenu/pull/2
